# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://itxx00.github.io
title: itxx00 blog page
email: itxx00@gmail.com
description: > # "Write some notes here"


# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/c0ak
  - title: github
    url: https://github.com/itxx00
