# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: cn
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://itxx00.github.io
baseurl: 
title: 运维老司机
description: "系好安全带，我要发车了。。。"
keywords: 'itxx00,运维'
author:
  name: itxx00
  job_title: ops
  location: ChengDu, China
  email: itxx00@gmail.com
  social_links:
    - name: facebook
      url:
    - name: github
      url: https://github.com/itxx00
    - name: linkedin
      url:
    - name: twitter
      url:
home:
  section1: <h1>运维老司机</h1>
blog:
  footer_content: 运维老司机

disqus:
  shortname:
  public_key:
google_analytics:
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
